### ISSUE TITLE
shape inconsistent after 'create_pair_batch'

### ISSUE THREAD

**Issue by yandacui** [cccnlab/CDT-API-Network#1]
Hi, when I train the model, the data after processed is nan, so the loss is also nan, can anyone help about this?

**Comment by waiiinta** [comment]
Hi, is all of the data nan or some of it? If all of it is nan, Could you give us image mean and std during each processes?

**Comment by yandacui** [comment]
Hi @waiiinta , thanks very much for your reply. I found out the issue seems happen here:
`X_aug_new_ord, X_aug_pair_new_ord, y_new_ord, y_pair_new_ord = create_pair_batch(X_aug_first, y_first,  X_aug_second, y_second, X_aug, y,  chosen_list_2, None, chosen_list_1)`
The len of input parameters `X_aug_first, y_first, X_aug_second, y_second, X_aug, y` are 32, it is normal, but after the function `create_pair_batch`, it returns empty list, and the len of output `X_aug_new_ord, X_aug_pair_new_ord, y_new_ord, y_pair_new_ord` is 0. And so the downstreaming train return error `File "/home/ubuntu/CDT-API-Network/train.py", line 366, in train_val_epoch           loss_log, grads = train_step(model,            TypeError: cannot unpack non-iterable NoneType object` 
Could you help have a look?

**Comment by waiiinta** [comment]
Could you check the length of `chosen_list_1` and `chosen_list_2`? I cannot replicate this error with the dataset in this repository. Are you using our provided dataset or your own dataset? 

The function `create_pair_batch` is only used to construct the batch base on given given `chosen_list_1` and `chosen_list_2`. The error possibly come from the empty list of `chosen_list_1` and `chosen_list_2`.

**Comment by yandacui** [comment]
I checked, the lengths of chosen_list_1 and chosen_list_2 are both 32. And I am using the dataset in this repository.

**Comment by waiiinta** [comment]
That's strange. Could you report this error with the providing bug reporting format? I have updated the format for this repository so that I can reproduce your error on my side.

**Comment by yandacui** [comment]
hmm. Okay it may be because I change to use Resnet50. Sorry, please ignore previous issue. Now I clone again to another folder, and I only changed  the batch size to 8 and epoch to 10 in train.py, this is because some OOM issue. But now I am facing a new issue like following. 
Traceback (most recent call last):
  File "/home/ubuntu/cdt_api/train.py", line 370, in <module>
    main()
  File "/home/ubuntu/cdt_api/train.py", line 96, in main
    train_loss_logs, val_loss_logs = train_val_epoch(
  File "/home/ubuntu/cdt_api/train.py", line 303, in train_val_epoch
    chosen_list_1 = construct_pair(X_aug_embedding, y,
  File "/home/ubuntu/cdt_api/util.py", line 140, in construct_pair
    dist = distance(X_1[i],X_1)
  File "/home/ubuntu/cdt_api/util.py", line 126, in distance
    l2_norm = euclidean_distances(point1.numpy().reshape(1, -1),point2.numpy())
  File "/opt/conda/envs/CDT-API-NETWORK/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 300, in euclidean_distances
    X, Y = check_pairwise_arrays(X, Y)
  File "/opt/conda/envs/CDT-API-NETWORK/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 155, in check_pairwise_arrays
    X = check_array(
  File "/opt/conda/envs/CDT-API-NETWORK/lib/python3.9/site-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/opt/conda/envs/CDT-API-NETWORK/lib/python3.9/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains infinity or a value too large for dtype('float32').

And I add log to check if the input data of distance calculation is inf.  I found that 
`
X_aug_embedding = model.get_embedding(X_aug)
X_aug_first_embedding = model.get_embedding(X_aug_first)
X_aug_second_embedding = model.get_embedding(X_aug_second)
`
X_aug, X_aug_first, X_aug_second are all normal and there is no inf value, but after this process, X_aug_embedding contains inf value, but X_aug_first_embedding and  X_aug_second_embedding has no inf value.

**Comment by waiiinta** [comment]
I still cannot reproduce your error. My code can run with your config.

![Screenshot 2024-04-07 210958](https://github.com/cccnlab/CDT-API-Network/assets/17044595/95e666fc-51c5-49de-ab8c-3d64c94320c9)

Could you check `X_aug` value contains infinite values? I think the image normalization process before feeding to the model may cause the input to have an inifinite value.

**Comment by yandacui** [comment]
X_aug has no inf values.

**Comment by waiiinta** [comment]
Hm, strange one. Normally, the model embedding should not have infinite values. Could you check the output from `imagenet_model` contains infinite value?

**Comment by yandacui** [comment]
The output of imagenet_model contains inf values. But also this only happens for X_aug.

**Comment by waiiinta** [comment]
Well, Could you check the min and max value of X_aug? and compare these values with the min and max from X_aug_first and X_aug_second.

**Comment by yandacui** [comment]
`max(X_aug) = 2.64, max(X_aug_first) = 2.64, max(X_aug_second) = 2.64, min(X_aug)= 7.248862e-05 , min(X_aug_first)=1.7029897e-05 , min(X_aug_second)= 1.5232298e-05`. after `embedding = self.imagenet_model(inputs)` in `model.get_embedding`, for X_aug,  max(embedding) =inf, for X_aug_first, max(embedding) = 9.6888944e+36,  for X_aug_second, max(embedding) = 1008953850000000.0.

**Comment by waiiinta** [comment]
Ok, I think there are some issues with your environment. I got max value of these embedding: X_aug = 21.095934, X_aug_first = 19.868685, and X_aug_second = 19.834143.

Could you check Tensorflow is using your GPU while training and check your CUDA matchs the CUDA requirement of Tensorflow?

**Comment by yandacui** [comment]
This is my tensorflow version, this matches the requirements. Is the cuda match the requirement? I didn't see there is any requirement of cuda.
tensorflow              2.4.1
tensorflow-estimator    2.6.0

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

And I run `conda env create -f environment.yml`. Can't this install all required packages?

**Comment by waiiinta** [comment]
It seems like Tensorflow 2.4 is updated its cuda to 11.0. Some dependencies in this repository are not updated and may cause the numerical miscalculation.

I think if you change tensorflow from 2.4.1 to 2.4, cudatoolkit to version 11.0, and cudnn to 8.0 in environment.yml, this should solve the error.

**Comment by yandacui** [comment]
Perfect, let me try it out. Thanks you!
